services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12Budapest99
    ports:
      - "27017:27017"
    volumes:
        - ./database/init.js:/docker-entrypoint-initdb.d/init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12Budapest99
      ME_CONFIG_MONGODB_URL: mongodb://root:12Budapest99@mongo:27017/

  backend:
    depends_on:
      - mongo
    build: ./backend
    restart: always
    ports:
      - 8080:8080

  frontend:
    depends_on:
      - backend
    build: ./frontend
    restart: always
    ports:
      - 8082:3000
  